steps:
  - simple_align:
      cases: false
      top_level_patterns: false
      records: false

  - imports:
      align: none
      list_align: after_alias
      pad_module_names: false
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false

  - language_pragmas:
      style: vertical
      align: false
      remove_redundant: true

  - tabs:
      spaces: 2

  - trailing_whitespace: {}

columns: 120

newline: lf

language_extensions:
  - DataKinds
  - ExplicitForAll
  - FlexibleContexts
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - Rank2Types
  - TemplateHaskell
  - TupleSections
  - TypeApplications
