name:                idream
version:             0.2.0.0
synopsis:            A simple build system for Idris
homepage:            https://github.com/ejconlon/idream#README.md
license:             BSD3
author:              idream team
maintainer:          idream team
copyright:           idream team, 2017
category:            Build Tool
extra-source-files:
- README.md

dependencies:
  - base >= 4.13 && < 5
  - aeson >= 1.5 && < 1.6
  - aeson-pretty >= 0.8 && < 0.9
  - algebraic-graphs >= 0.5 && < 0.6
  - bytestring >= 0.10 && < 0.11
  - containers >= 0.6 && < 0.7
  - data-default >= 0.7 && < 0.8
  - directory >= 1.3 && < 1.4
  - filepath >= 1.4 && < 1.5
  - little-logger >= 0.3 && < 0.4
  - little-rio >= 0.2 && < 0.3
  - microlens >= 0.4 && < 0.5
  - mtl >= 2.2 && < 2.3
  - optparse-applicative >= 0.15 && < 0.16
  - process >= 1.6 && < 1.7
  - shelly >= 1.9 && < 1.10
  - text >= 1.2 && < 1.3
  - unliftio >= 0.2 && < 0.3

ghc-options: -Wall -Werror -optP-Wno-nonportable-include-path  # -O2

default-extensions:
  - DeriveFoldable
  - OverloadedStrings

library:
  source-dirs: src

executables:
  idream:
    source-dirs:  exe
    main:         Main.hs
    dependencies:
      - idream

tests:
  idream-test:
    main:         test.hs
    source-dirs:  test
    dependencies:
      - idream
      - tasty >= 1.2 && < 1.3
      - tasty-discover >= 4.2 && < 4.3
      - tasty-hspec >= 1.1 && < 1.2
