module Idream.Types where
--   ( ProjectName (..)
--   , PackageName (..)
--   , Argument
--   , SourceDir (..)
--   , Repo (..)
--   , Version (..)
--   , Project (..)
--   , Package (..)
--   , Dependency (..)
--   , PackageSet (..)
--   , PackageType (..)
--   , Command (..)
--   , Args (..)
--   ) where

-- import Control.Applicative (empty)
-- import Data.Aeson (FromJSON (..), FromJSONKey (..), ToJSON (..), ToJSONKey (..), Value (..), object, withText, withObject, (.!=), (.:), (.:?), (.=))
-- import Data.Map (Map)
-- import Data.Text (Text)
-- import Data.String (IsString)
-- import Idream.FilePaths (Directory)
-- import Idream.ToText (ToText (..))
-- import LittleLogger (Severity)
